### ISSUE TITLE
is_day and precipitation_probability appear to be missing from 'Hourly' class

### ISSUE THREAD

**Issue by chumplybum** [AlienDwarf/open-meteo-dotnet#23]
Hi AlienDwarf, thanks for the library

As above, i'm unable to find the 'is_day' or 'precipitation_probability' properties within the 'Hourly' class. I've also just looked at the kotlin library and it also appears to be missing there as well.

**Comment by chumplybum** [comment]
thankyou. Works great!

**Comment by AlienDwarf** [comment]
Hello @chumplybum 

thank you very much for your bug report!

My first reply was not sent due to connection problems.

I haven't updated the current branch lately as I'm working on v0.3. The new variables are all there already, but I'm trying to maintain compatibility with old code, so the release will take some time. I applied a hotfix which works as long as you don't use "WeatherModels".

Please let me know if you find any additional bugs :)
